# Apache License
# Version 2.0, January 2004
# Author: Jonathan Tiritilli

name: 'OpenAPI TOC Generator for Mintlify'
description: 'Generate Mintlify docs.json navigation entries from OpenAPI YAML specifications'
author: 'Jonathan Tiritilli'
branding:
  icon: book-open
  color: green

inputs:
  yaml_input_path:
    description: 'Path to directory containing OpenAPI YAML files'
    required: false
    default: './yaml'
  docs_json_path:
    description: 'Path to Mintlify docs.json file to update'
    required: true
  openapi_base_path:
    description: 'Base path for OpenAPI references in docs.json (e.g., "openapi/product")'
    required: false
    default: 'openapi/product'
  yaml_copy_destination:
    description: 'Optional directory to copy YAML files to after processing'
    required: false
    default: ''
  process_changed_only:
    description: 'Only process YAML files that have changed (requires git history)'
    required: false
    default: 'false'
  changed_files:
    description: 'Newline-separated list of changed files to process (overrides internal change detection)'
    required: false
    default: ''
  base_ref:
    description: 'Base reference for change detection (default: main branch or PR base)'
    required: false
    default: ''
  create_pull_request:
    description: 'Create a pull request with the updated docs.json'
    required: false
    default: 'false'
  pr_title:
    description: 'Title for the pull request'
    required: false
    default: 'Update API navigation in docs.json'
  pr_branch_name:
    description: 'Name for the PR branch'
    required: false
    default: 'docs/update-api-navigation'

outputs:
  files_processed:
    description: 'Number of YAML files processed'
    value: ${{ steps.generate.outputs.files_processed }}
  groups_updated:
    description: 'Number of API groups updated in docs.json'
    value: ${{ steps.generate.outputs.groups_updated }}

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Detect changed YAML files
      id: changed-yaml
      shell: bash
      run: |
        if [[ "${{ inputs.process_changed_only }}" == "true" ]]; then
          echo "Detecting changed YAML files..."

          # Determine base reference
          if [[ -n "${{ inputs.base_ref }}" ]]; then
            BASE_REF="${{ inputs.base_ref }}"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_REF="${{ github.event.pull_request.base.sha }}"
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            BASE_REF="${{ github.event.before }}"
          else
            BASE_REF="origin/main"
          fi

          echo "Base reference: $BASE_REF"

          # Get changed YAML files
          YAML_DIR=$(echo "${{ inputs.yaml_input_path }}" | sed 's|^\./||')
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT "$BASE_REF"...HEAD | grep -E '\.(yaml|yml)$' | grep "^${YAML_DIR}/" || true)

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No YAML files changed in ${{ inputs.yaml_input_path }}"
            echo "changed_files=" >> $GITHUB_OUTPUT
            echo "has_changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Changed YAML files:"
          echo "$CHANGED_FILES" | sed 's/^/  - /'

          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "Processing all YAML files in directory"
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "changed_files=" >> $GITHUB_OUTPUT
        fi

    - name: Check if processing needed
      id: should-process
      shell: bash
      run: |
        if [[ -n "${{ inputs.changed_files }}" ]]; then
          echo "should_process=true" >> $GITHUB_OUTPUT
        elif [[ "${{ steps.changed-yaml.outputs.has_changes }}" != "true" ]]; then
          echo "No changes detected, skipping processing"
          echo "## No Changes Detected" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "No YAML files have changed since last run." >> $GITHUB_STEP_SUMMARY
          echo "should_process=false" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "should_process=true" >> $GITHUB_OUTPUT
        fi

    - name: Verify paths
      if: steps.should-process.outputs.should_process == 'true'
      shell: bash
      run: |
        # Verify input directory exists
        if [[ ! -d "${{ inputs.yaml_input_path }}" ]]; then
          echo "Error: Input directory not found: ${{ inputs.yaml_input_path }}"
          exit 1
        fi

        # Verify docs.json exists
        if [[ ! -f "${{ inputs.docs_json_path }}" ]]; then
          echo "Error: docs.json not found: ${{ inputs.docs_json_path }}"
          exit 1
        fi

        # Count YAML files
        YAML_COUNT=$(find "${{ inputs.yaml_input_path }}" -name "*.yaml" -o -name "*.yml" | wc -l)
        echo "Found $YAML_COUNT YAML file(s) in ${{ inputs.yaml_input_path }}"

        if [[ $YAML_COUNT -eq 0 ]]; then
          echo "Warning: No YAML files found"
        fi

    - name: Create copy destination directory
      if: steps.should-process.outputs.should_process == 'true' && inputs.yaml_copy_destination != ''
      shell: bash
      run: |
        mkdir -p "${{ inputs.yaml_copy_destination }}"
        echo "Created copy destination: ${{ inputs.yaml_copy_destination }}"

    - name: Generate TOC and update docs.json
      if: steps.should-process.outputs.should_process == 'true'
      id: generate
      shell: bash
      env:
        YAML_INPUT_PATH: ${{ inputs.yaml_input_path }}
        DOCS_JSON_PATH: ${{ inputs.docs_json_path }}
        OPENAPI_BASE_PATH: ${{ inputs.openapi_base_path }}
        YAML_COPY_DESTINATION: ${{ inputs.yaml_copy_destination }}
        PROCESS_CHANGED_ONLY: ${{ inputs.process_changed_only }}
        CHANGED_FILES: ${{ inputs.changed_files || steps.changed-yaml.outputs.changed_files }}
      run: |
        echo "Starting TOC generation..."
        echo "  Input: ${{ inputs.yaml_input_path }}"
        echo "  docs.json: ${{ inputs.docs_json_path }}"
        echo "  Base path: ${{ inputs.openapi_base_path }}"

        python "${{ github.action_path }}/src/toc_generator_main.py"

        echo "TOC generation complete"

    - name: Compute branch suffix
      if: inputs.create_pull_request == 'true' && steps.should-process.outputs.should_process == 'true'
      id: branch-suffix
      shell: bash
      run: |
        # Build a stable hash from the sorted list of processed files
        # so the same set of changed files always maps to the same branch/PR
        if [[ -n "${{ inputs.changed_files }}" ]]; then
          FILE_LIST="${{ inputs.changed_files }}"
        elif [[ -n "${{ steps.changed-yaml.outputs.changed_files }}" ]]; then
          FILE_LIST="${{ steps.changed-yaml.outputs.changed_files }}"
        else
          # Processing all files - list everything in the input directory
          FILE_LIST=$(find "${{ inputs.yaml_input_path }}" -name "*.yaml" -o -name "*.yml" | sort)
        fi

        HASH=$(echo "$FILE_LIST" | sort | sha256sum | cut -c1-8)
        echo "hash=$HASH" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: inputs.create_pull_request == 'true' && steps.should-process.outputs.should_process == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ github.token }}
        commit-message: 'docs: Update API navigation in docs.json'
        title: ${{ inputs.pr_title }}
        body: |
          ## API Navigation Update

          This PR updates the Mintlify docs.json navigation with TOC entries generated from OpenAPI specifications.

          ### Summary
          - **Files processed:** ${{ steps.generate.outputs.files_processed }}
          - **Groups updated:** ${{ steps.generate.outputs.groups_updated }}

          ### Configuration
          - **YAML input path:** `${{ inputs.yaml_input_path }}`
          - **OpenAPI base path:** `${{ inputs.openapi_base_path }}`
          - **Change detection:** ${{ inputs.process_changed_only == 'true' && 'Enabled' || 'Disabled' }}

          ---
          Generated by [OpenAPI TOC Generator](https://github.com/DomoApps/documentation-generator-action)
        branch: ${{ inputs.pr_branch_name }}-${{ steps.branch-suffix.outputs.hash }}
        delete-branch: true
        add-paths: |
          ${{ inputs.docs_json_path }}
          ${{ inputs.yaml_copy_destination }}/**
        assignees: ${{ github.actor }}

    - name: Summary
      if: steps.should-process.outputs.should_process == 'true'
      shell: bash
      run: |
        echo "## TOC Generation Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Files processed:** ${{ steps.generate.outputs.files_processed || 'N/A' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Groups updated:** ${{ steps.generate.outputs.groups_updated || 'N/A' }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Configuration" >> $GITHUB_STEP_SUMMARY
        echo "- **YAML input:** \`${{ inputs.yaml_input_path }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **docs.json:** \`${{ inputs.docs_json_path }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Base path:** \`${{ inputs.openapi_base_path }}\`" >> $GITHUB_STEP_SUMMARY

        if [ "${{ inputs.create_pull_request }}" == "true" ]; then
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Pull Request" >> $GITHUB_STEP_SUMMARY
          echo "A pull request has been created with the changes." >> $GITHUB_STEP_SUMMARY
        fi
