name: Sync API Documentation from Source Repo

# This workflow runs autonomously in the destination repo - NO secrets needed in source repo!
# It can be triggered three ways:
# 1. Schedule: Runs every 6 hours, checks source repo for changes
# 2. Manual: Use workflow_dispatch to run on demand
# 3. Source notification: Optional repository_dispatch from source repo (requires source repo secrets)

on:
  # Primary trigger - runs automatically every 6 hours
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

  # Manual trigger - use this for on-demand sync
  workflow_dispatch:
    inputs:
      force_regenerate:
        description: 'Force regenerate all docs (ignore change detection)'
        required: false
        type: boolean
        default: false

  # Optional - only works if source repo has APP_ID and APP_PRIVATE_KEY secrets configured
  repository_dispatch:
    types: [source-yaml-updated]

jobs:
  sync_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: domoinc
          repositories: internal-domo-apis

      - name: Checkout Destination Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Source Repo
        uses: actions/checkout@v4
        with:
          repository: domoinc/internal-domo-apis
          token: ${{ steps.app-token.outputs.token }}
          path: source-repo
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      # Cross-repo change detection: Compare source YAML timestamps with destination markdown
      # This is needed because we're syncing between two repos - git diff wouldn't detect these changes
      - name: Detect Changed YAML Files
        id: detect
        run: |
          python .github/scripts/detect_yaml_changes.py \
            --source source-repo/api-docs/public \
            --dest docs/API-Reference/Product-APIs \
            --mapping .github/doc-mapping.json \
            --force ${{ github.event.inputs.force_regenerate || 'false' }}

      - name: Check if Changes Detected
        id: check
        run: |
          if [ -f changed_files.txt ] && [ -s changed_files.txt ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changed files detected:"
            cat changed_files.txt
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      # Read changed files list
      - name: Read Changed Files
        if: steps.check.outputs.has_changes == 'true'
        id: read-changes
        run: |
          {
            echo "changed_files<<EOF"
            cat changed_files.txt
            echo "EOF"
          } >> $GITHUB_OUTPUT

      # Generate documentation (action only generates, does not create PRs)
      - name: Generate Documentation
        if: steps.check.outputs.has_changes == 'true'
        uses: DomoApps/documentation-generator-action@main
        with:
          # Required
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

          # Paths
          yaml_input_path: './source-repo/api-docs/public'
          output_path: './temp-docs'
          template_path: 'default'  # or path to custom template

          # AI Configuration
          openai_model: 'gpt-4o'  # or 'gpt-4', 'gpt-3.5-turbo'
          max_iterations: '3'  # Max refinement iterations (higher = better quality, more cost)
          completeness_threshold: '90'  # Quality score threshold (0-100)
          timeout_minutes: '30'  # Max processing time

          # Change Detection
          changed_files: ${{ steps.read-changes.outputs.changed_files }}
          process_changed_only: 'false'  # We already filtered via detect_yaml_changes.py

          # PR creation disabled - we handle it below with sync
          create_pull_request: 'false'

      # Create individual PRs with proper file mapping
      - name: Create Individual PRs with File Sync
        if: steps.check.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          python .github/scripts/create_individual_prs.py \
            --changed-list changed_files.txt \
            --temp-dir ./temp-docs \
            --dest-dir docs/API-Reference/Product-APIs \
            --mapping-file .github/doc-mapping.json \
            --sync-script .github/scripts/sync_to_destination.py \
            --base-branch master \
            --pr-branch-prefix doc-bot \
            --openai-model gpt-4o \
            --max-iterations 3 \
            --completeness-threshold 90 \
            --repo DomoApps/domo-developer-portal

      - name: Summary
        if: always()
        run: |
          echo "## ðŸ“š Documentation Sync Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.check.outputs.has_changes }}" == "true" ]; then
            echo "âœ… Changes detected and processed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Changed Files:" >> $GITHUB_STEP_SUMMARY
            if [ -f changed_files.txt ]; then
              while IFS= read -r file; do
                echo "- \`$file\`" >> $GITHUB_STEP_SUMMARY
              done < changed_files.txt
            fi
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Actions Taken:" >> $GITHUB_STEP_SUMMARY
            echo "- Generated documentation from OpenAPI/YAML specs" >> $GITHUB_STEP_SUMMARY
            echo "- Applied file mapping configuration to destination paths" >> $GITHUB_STEP_SUMMARY
            echo "- Created individual PR per file (skipped files with existing open PRs)" >> $GITHUB_STEP_SUMMARY
            echo "- Committed files to proper destination locations (not temp-docs)" >> $GITHUB_STEP_SUMMARY
          else
            echo "â„¹ï¸ No changes detected - documentation is up to date" >> $GITHUB_STEP_SUMMARY
          fi
