# With Change Detection
# Only processes YAML files that have changed since last run

name: Update API Navigation (Changed Only)

on:
  push:
    branches: [main]
    paths:
      - 'yaml/**/*.yaml'
      - 'yaml/**/*.yml'
  pull_request:
    paths:
      - 'yaml/**/*.yaml'
      - 'yaml/**/*.yml'

jobs:
  update-navigation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for change detection

      - name: Generate API Navigation
        uses: DomoApps/documentation-generator-action@main
        with:
          yaml_input_path: './yaml'
          docs_json_path: './docs.json'
          openapi_base_path: 'openapi/product'
          process_changed_only: 'true'

      - name: Commit changes
        if: github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs.json
          git diff --staged --quiet || git commit -m "docs: Update API navigation"
          git push
