# With Pull Request Creation
# Creates a PR with navigation updates for review instead of direct commit

name: Update API Navigation (PR)

on:
  push:
    branches: [main]
    paths:
      - 'yaml/**/*.yaml'
      - 'yaml/**/*.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-navigation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate API Navigation
        uses: DomoApps/documentation-generator-action@main
        with:
          yaml_input_path: './yaml'
          docs_json_path: './docs.json'
          openapi_base_path: 'openapi/product'
          process_changed_only: 'true'
          create_pull_request: 'true'
          pr_title: 'docs: Update API navigation'
          pr_branch_name: 'docs/api-navigation-update'
