# Test workflow for the YAML to Markdown Documentation Generator
name: Test Action

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-composite-action:
    name: Test Composite Action
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.repository_owner == 'eps'  # Only run on PRs or in main org
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test input directory
        run: |
          mkdir -p test-input
          cp samples/filesets.yaml test-input/

      - name: Test Composite Action
        id: test-action
        uses: ./
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY || 'fake-key-for-testing' }}
          yaml_input_path: './test-input'
          output_path: './test-output'
          max_iterations: '2'  # Reduced for testing
          timeout_minutes: '5'  # Reduced for testing
        continue-on-error: true  # Don't fail the workflow if API key is missing

      - name: Verify output structure
        run: |
          echo "🔍 Checking test results..."

          if [ -d "./test-output" ]; then
            echo "✅ Output directory created"
            ls -la ./test-output
          else
            echo "❌ Output directory not found"
            exit 1
          fi

          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "⚠️  OPENAI_API_KEY not available - skipping content validation"
            echo "This is expected for forks and pull requests"
          else
            echo "✅ API key available - action should have run successfully"
            echo "Files generated: ${{ steps.test-action.outputs.files_generated }}"
          fi

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-output
          path: ./test-output
          retention-days: 7

  test-python-imports:
    name: Test Python Module Imports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test imports
        run: |
          echo "🐍 Testing Python imports..."
          python -c "import sys; sys.path.append('src'); from ai.doc_generator import DocGenerator; print('✅ DocGenerator imports successfully')"
          python -c "import sys; sys.path.append('src'); from doc_generator_main import main; print('✅ Main module imports successfully')"
          python -c "import sys; sys.path.append('src'); from env_vars import EnvVars; print('✅ EnvVars imports successfully')"

      - name: Run unit tests
        run: |
          echo "🧪 Running unit tests..."
          python -m pytest tests/ -v

  validate-action-yaml:
    name: Validate Action YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate action.yml
        run: |
          echo "📋 Validating action.yml structure..."

          # Check required fields exist
          if ! grep -q "name:" action.yml; then
            echo "❌ Missing 'name' field in action.yml"
            exit 1
          fi

          if ! grep -q "description:" action.yml; then
            echo "❌ Missing 'description' field in action.yml"
            exit 1
          fi

          if ! grep -q "runs:" action.yml; then
            echo "❌ Missing 'runs' field in action.yml"
            exit 1
          fi

          echo "✅ action.yml structure is valid"

      - name: Validate workflow YAML
        run: |
          echo "📋 Validating workflow YAML..."

          # Check workflow file exists and has required structure
          if [ ! -f ".github/workflows/action.yml" ]; then
            echo "❌ Workflow file not found"
            exit 1
          fi

          if ! grep -q "workflow_call:" .github/workflows/action.yml; then
            echo "❌ Missing workflow_call trigger"
            exit 1
          fi

          echo "✅ Workflow YAML structure is valid"

  test-documentation:
    name: Test Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check documentation files
        run: |
          echo "📚 Checking documentation files..."

          required_files=("README.md" "CHANGELOG.md" "RELEASES.md" "action.yml" "samples/filesets.yaml" "samples/productAPI.template.md")

          for file in "${required_files[@]}"; do
            if [ -f "$file" ]; then
              echo "✅ Found: $file"
            else
              echo "❌ Missing: $file"
              exit 1
            fi
          done

          echo "✅ All required documentation files present"

      - name: Validate sample files
        run: |
          echo "🔍 Validating sample files..."

          # Check if sample YAML is valid
          python -c "import yaml; yaml.safe_load(open('samples/filesets.yaml'))" && echo "✅ filesets.yaml is valid YAML" || echo "❌ Invalid YAML in filesets.yaml"

          # Check if template file has placeholders
          if grep -q "{{" samples/productAPI.template.md; then
            echo "✅ Template file contains placeholders"
          else
            echo "❌ Template file missing placeholders"
            exit 1
          fi